apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wak75/argoCd.git
    targetRevision: HEAD
    path: all/yamls/  # Create a folder named 'all' in the repository and place all files in it
  destination:
    server: https://kubernetes.default.svc
    namespace: kingnamespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 

    automated:
      selfHeal: true
      prune: true
